function [nodes, edges] = graphConfig()
%GRAPHCONFIG  SerDes graph definition — node specs and edge topology.
%
%   [nodes, edges] = graphConfig() returns all node definitions and the
%   edges that wire them into a DAG. This is the SerDes-specific
%   application of the +agentgraph framework.

    nodes = [
        agentgraph.AgentNode("build", ...
            ToolNames = ["createSerdesSystem","configureChannel","configureAnalogModel", ...
                         "configureCTLE","configureDFECDR","configureVGA","configureFFE", ...
                         "getSystemState"], ...
            SystemPrompt = readPrompt("build.md"), ...
            Description = "Build the SerDes system from the request (channel, " + ...
                "equalization). Usually reached only as an ancestor of a later goal.", ...
            MaxIterations = 20)

        agentgraph.AgentNode("analyse", ...
            ToolNames = ["runAnalysis","getAnalysisResults","getSystemState"], ...
            SystemPrompt = readPrompt("analyse.md"), ...
            Description = "Run statistical analysis and read the reported eye metrics. " + ...
                "Drive here first to see if optimization is needed.", ...
            MaxIterations = 10)

        agentgraph.AgentNode("optimize", ...
            ToolNames = ["sweepParameter","optimizeWithGA","runAnalysis", ...
                         "getAnalysisResults","getSystemState","configureCTLE", ...
                         "configureDFECDR","configureFFE","configureVGA"], ...
            SystemPrompt = readPrompt("optimize.md"), ...
            Description = "Optimize equalization: sweep parameters or run GA to maximize " + ...
                "eye height / COM. Re-drive with taskmasterHint until metrics are satisfactory.", ...
            MaxIterations = 25)

        agentgraph.AgentNode("plot", ...
            ToolNames = ["plotSerdesResults","plotSweepResults","getAnalysisResults", ...
                         "getSystemState"], ...
            SystemPrompt = readPrompt("plot.md"), ...
            Description = "Produce the final eye diagram and measurements. Drive here " + ...
                "once the eye height is satisfactory.", ...
            MaxIterations = 10)
    ];

    edges = [
        "build",    "analyse"
        "analyse",  "optimize"
        "optimize", "plot"
    ];
end

function p = readPrompt(filename)
    promptDir = fullfile(fileparts(mfilename('fullpath')), "prompts");
    p = string(fileread(fullfile(promptDir, filename)));
end
