classdef tLLMClient < matlab.unittest.TestCase
% Tests for the LLMClient factory function.

%   Copyright 2026 The MathWorks, Inc.

    properties (TestParameter)
        ApiConfig = struct( ...
            "openai", struct("api", "openai", "model", "gpt-4o", "class", "aisdk.llms.client.OpenAIClient"), ...
            "ollama", struct("api", "ollama", "model", "llama2", "class", "aisdk.llms.client.OllamaClient"));
    end

    methods (Test, TestTags = {'Unit'}, ParameterCombination="sequential")
        function createsCorrectClientType(testCase, ApiConfig)
            client = aisdk.LLMClient(ApiConfig.api, ApiConfig.model);
            testCase.verifyClass(client, ApiConfig.class);
            testCase.verifyEqual(client.ModelName, ApiConfig.model);
        end
    end

    methods (Test, TestTags = {'Unit'})
        function invalidApiErrors(testCase)
            testCase.verifyError(...
                @() aisdk.LLMClient("someAPIThatDoesNotExist", "gpt-4o"), ...
                "MATLAB:validators:mustBeMember");
        end

        function errorWhenModelNameOmitted(testCase)
            testCase.verifyError(...
                @() aisdk.LLMClient("openai"), ...
                "MATLAB:minrhs");
        end

        function errorWhenAllArgsOmitted(testCase)
            testCase.verifyError(...
                @() aisdk.LLMClient(), ...
                "MATLAB:minrhs");
        end

        function openaiPassesNameValuePairsThrough(testCase)
            streamFcn = @(x) disp(x);
            client = aisdk.LLMClient("openai", "gpt-4o", ...
                Temperature=0.5, ...
                TopP=0.9, ...
                StopSequences=["stop1", "stop2"], ...
                MaxNumTokens=100, ...
                PresencePenalty=0.3, ...
                FrequencyPenalty=0.4, ...
                ResponseFormat="json", ...
                ReasoningEffort="high", ...
                Verbosity="low", ...
                TimeOut=30, ...
                StreamFcn=streamFcn, ...
                BaseURL="https://fake.endpoint");
            testCase.verifyEqual(client.Temperature, 0.5);
            testCase.verifyEqual(client.TopP, 0.9);
            testCase.verifyEqual(client.StopSequences, ["stop1", "stop2"]);
            testCase.verifyEqual(client.MaxNumTokens, 100);
            testCase.verifyEqual(client.PresencePenalty, 0.3);
            testCase.verifyEqual(client.FrequencyPenalty, 0.4);
            testCase.verifyEqual(client.ResponseFormat, "json");
            testCase.verifyEqual(client.ReasoningEffort, "high");
            testCase.verifyEqual(client.Verbosity, "low");
            testCase.verifyEqual(client.TimeOut, 30);
            testCase.verifyEqual(client.StreamFcn, streamFcn);
            testCase.verifyEqual(client.BaseURL, "https://fake.endpoint/chat/completions");
        end

        function ollamaPassesNameValuePairsThrough(testCase)
            streamFcn = @(x) disp(x);
            client = aisdk.LLMClient("ollama", "llama2", ...
                Temperature=0.5, ...
                TopP=0.9, ...
                MinP=0.1, ...
                TopK=50, ...
                TailFreeSamplingZ=0.95, ...
                StopSequences=["stop1", "stop2"], ...
                MaxNumTokens=100, ...
                ResponseFormat="json", ...
                TimeOut=30, ...
                StreamFcn=streamFcn, ...
                BaseURL="http://localhost:11434");
            testCase.verifyEqual(client.Temperature, 0.5);
            testCase.verifyEqual(client.TopP, 0.9);
            testCase.verifyEqual(client.MinP, 0.1);
            testCase.verifyEqual(client.TopK, 50);
            testCase.verifyEqual(client.TailFreeSamplingZ, 0.95);
            testCase.verifyEqual(client.StopSequences, ["stop1", "stop2"]);
            testCase.verifyEqual(client.MaxNumTokens, 100);
            testCase.verifyEqual(client.ResponseFormat, "json");
            testCase.verifyEqual(client.TimeOut, 30);
            testCase.verifyEqual(client.StreamFcn, streamFcn);
            testCase.verifyEqual(client.BaseURL, "http://localhost:11434/api/chat");
        end
    end

end
