classdef tMCPClient < matlab.unittest.TestCase
%Tests for aisdk.MCPClient using the mock connection type.

% Copyright 2026 The MathWorks, Inc.

    methods (TestClassSetup)
        function addToPath(testCase)
            testDir = fileparts(mfilename("fullpath"));
            projectRoot = fileparts(testDir);
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(projectRoot));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(testDir, "helpers")));
        end
    end

    methods (Test, TestTags = {'Unit'})
        function tools_includeInputSchema(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            schema = client.Tools(1).InputSchema;
            testCase.verifyTrue(isstruct(schema));
            testCase.verifyTrue(isfield(schema, "properties"));
            testCase.verifyEqual(schema.type, 'object');
        end

        function tools_evaluate_resultHasIsErrorFalse(testCase)
            import matlab.unittest.constraints.HasField
            client = aisdk.MCPClient("mock", Transport="mock");
            result = client.Tools(1).evaluate(struct("param1", "hello"));
            testCase.verifyThat(result, HasField("isError"));
            testCase.verifyFalse(result.isError);
        end

        function callTool_structArg_returnsResult(testCase)
            % callTool is a private seam; the struct-argument form is not
            % reachable through the public Tools array.
            client = aisdk.MCPClient("mock", Transport="mock");
            tool = struct("name", "example-tool", ...
                "arguments", struct("param1", "hello", "param2", 42));
            result = client.callTool(tool);
            testCase.verifyEqual(result.content.text, 'Example result');
        end

        function callTool_structArgWithJsonStringArguments_returnsResult(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            tool = struct("name", "example-tool", ...
                "arguments", '{"param1":"hello"}');
            result = client.callTool(tool);
            testCase.verifyEqual(result.content.text, 'Example result');
        end

        function callTool_structArgWithNoArguments_returnsResult(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            tool = struct("name", "example-tool");
            result = client.callTool(tool);
            testCase.verifyEqual(result.content.text, 'Example result');
        end

        function callTool_unknownTool_errors(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            testCase.verifyError(...
                @() client.callTool("nonexistent-tool", "x", 1), ...
                "aisdk:MCPClient:serverError");
        end

        function callTool_unpairedNameValueArgs_errors(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            testCase.verifyError(...
                @() client.callTool("example-tool", "param1"), ...
                "aisdk:MCPClient:oddNameValuePairs");
        end

        function constructor_invalidTransport_errors(testCase)
            testCase.verifyError(...
                @() aisdk.MCPClient("mock", Transport="bogus"), ...
                "MATLAB:validators:mustBeMember");
        end

        function constructor_nonScalarEndpointWithNonStdio_errors(testCase)
            testCase.verifyError(...
                @() aisdk.MCPClient(["a", "b"], Transport="sse"), ...
                "aisdk:MCPClient:nonScalarURL");
        end

        function delete_disconnectsFromServer(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            testCase.verifyNotEmpty(client.Tools);
            delete(client);
            logs = aisdk.internal.mcpclient_mex("getLogs");
            testCase.verifySubstring(logs, "Connection closed");
        end

        function getLogs_afterConnect_containsConnectionCreated(testCase)
            client = aisdk.MCPClient("mock", Transport="mock"); %#ok<NASGU>
            logs = aisdk.internal.mcpclient_mex("getLogs");
            testCase.verifySubstring(logs, "Connection created");
        end

        function tools_returnsTypedMCPToolVector(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            tools = client.Tools;
            testCase.verifyClass(tools, "aisdk.llms.tool.MCPTool");
            testCase.verifyNotEmpty(tools);
            testCase.verifyEqual(tools(1).Name, "example-tool");
            testCase.verifyEqual(tools(1).Description, "An example tool for testing");
        end

        function tools_canBeCalled(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            tools = client.Tools;
            result = tools(1).evaluate(struct("param1", "hello", "param2", 42));
            testCase.verifyEqual(result.content.text, 'Example result');
        end

        function callTool_viaEvaluate_preservesArrayParams(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            tools = client.Tools;
            args = struct("param1", "hello");
            args.items = {"a", "b"};
            result = tools(1).evaluate(args);
            testCase.verifyEqual(result.content.text, 'Example result');
        end

        function callTool_nonAsciiArgument_roundTripsUnchanged(testCase, NonAsciiText)
            % MCP is UTF-8 throughout. Argument values must survive the trip
            % out through the MEX and back, unchanged. The mock's echo tool
            % returns its arguments JSON-encoded, so any mangling shows up in
            % the decoded result.
            client = aisdk.MCPClient("mock", Transport="mock");
            echoTool = client.Tools([client.Tools.Name] == "echo");
            testCase.assertNumElements(echoTool, 1, ...
                "mock should expose one echo tool");

            result = echoTool.evaluate(struct("text", NonAsciiText));

            echoed = jsondecode(string(result.content.text));
            testCase.verifyEqual(string(echoed.text), NonAsciiText);
        end

        function callTool_nonAsciiResult_isReturnedUnchanged(testCase)
            % The response direction alone: the request is pure ASCII, only
            % the server's reply carries non-ASCII text.
            client = aisdk.MCPClient("mock", Transport="mock");
            echoTool = client.Tools([client.Tools.Name] == "echo");

            result = echoTool.evaluate(struct("text", "café 東京 🎉"));

            testCase.verifySubstring(string(result.content.text), "café 東京 🎉");
        end

        function connect_nonAsciiEndpoint_succeeds(testCase)
            % Endpoints reach the MEX as MATLAB strings, the same path a
            % stdio command in a folder with a non-ASCII name takes. The mock
            % ignores its URL, so this isolates the conversion.
            client = aisdk.MCPClient("mock-café-東京-🎉", Transport="mock");
            testCase.verifyNotEmpty(client.Tools);
        end

        function constructor_timeOutOption_setsProperty(testCase)
            % TimeOut has to be settable at construction: the first listTools
            % runs inside the constructor, so a value assigned afterwards
            % arrives too late to govern it.
            client = aisdk.MCPClient("mock", Transport="mock", TimeOut=5);
            testCase.verifyEqual(client.TimeOut, 5);
        end

        function constructor_withoutTimeOut_usesDefault(testCase)
            client = aisdk.MCPClient("mock", Transport="mock");
            testCase.verifyEqual(client.TimeOut, 120);
        end

        function constructor_negativeTimeOut_errors(testCase)
            testCase.verifyError( ...
                @() aisdk.MCPClient("mock", Transport="mock", TimeOut=-1), ...
                "MATLAB:validators:mustBeNonnegative");
        end

        function toolPrefix_prefixesToolNames(testCase)
            client = aisdk.MCPClient("mock", Transport="mock", ...
                ToolPrefix="astro");
            testCase.verifyEqual(client.Tools(1).Name, "astro_example-tool");
        end

        function toolPrefix_prefixedTool_isCallable(testCase)
            % The public tool carries the prefixed name but still resolves
            % to the raw server tool when evaluated.
            client = aisdk.MCPClient("mock", Transport="mock", ...
                ToolPrefix="astro");
            tool = client.Tools(1);
            testCase.verifyEqual(tool.Name, "astro_example-tool");
            result = tool.evaluate(struct("param1", "hello"));
            testCase.verifyEqual(result.content.text, 'Example result');
        end

        function toolPrefix_callToolWithPrefix_succeeds(testCase)
            % callTool is a private seam; the prefixed-name resolution path
            % is not reachable through the public Tools array.
            client = aisdk.MCPClient("mock", Transport="mock", ...
                ToolPrefix="astro");
            result = client.callTool("astro_example-tool", "param1", "hello");
            testCase.verifyEqual(result.content.text, 'Example result');
        end

        function toolPrefixWithInvalidChars_errors(testCase)
            testCase.verifyError(...
                @() aisdk.MCPClient("mock", Transport="mock", ...
                    ToolPrefix="bad-name"), ...
                "aisdk:MCPClient:invalidToolPrefix");
            testCase.verifyError(...
                @() aisdk.MCPClient("mock", Transport="mock", ...
                    ToolPrefix="2bad"), ...
                "aisdk:MCPClient:invalidToolPrefix");
        end

        function emptyToolPrefix_doesNotPrefix(testCase)
            client = aisdk.MCPClient("mock", Transport="mock", ...
                ToolPrefix="");
            testCase.verifyEqual(client.Tools(1).Name, "example-tool");
        end

        function saveAndLoad_restoresToolsAndCanCallThem(testCase)
            client = aisdk.MCPClient("mock", Transport="mock", ...
                ToolPrefix="srv");
            testCase.verifyNotEmpty(client.Tools);

            f = [tempname, '.mat'];
            testCase.addTeardown(@() delete(f));
            save(f, "client");
            loaded = load(f);

            testCase.verifyNotEmpty(loaded.client.Tools);
            testCase.verifyEqual(loaded.client.Tools(1).Name, "srv_example-tool");
            % The loaded client must be functional — its tools can be evaluated.
            result = loaded.client.Tools(1).evaluate(struct("param1", "hi"));
            testCase.verifyEqual(result.content.text, 'Example result');
        end
    end

    properties (TestParameter)
        HttpErrorCase = struct( ...
            "unauthorized", struct( ...
                "statusCode", 401, ...
                "expectedId", "aisdk:MCPClient:unauthorized"), ...
            "forbidden", struct( ...
                "statusCode", 403, ...
                "expectedId", "aisdk:MCPClient:forbidden"), ...
            "notFound", struct( ...
                "statusCode", 404, ...
                "expectedId", "aisdk:MCPClient:notFound"), ...
            "methodNotAllowed", struct( ...
                "statusCode", 405, ...
                "expectedId", "aisdk:MCPClient:methodNotAllowed"), ...
            "badGateway", struct( ...
                "statusCode", 502, ...
                "expectedId", "aisdk:MCPClient:badGateway"))
        MexErrorCase = struct( ...
            "badInput", struct( ...
                "identifier", "mcpclient_mex:badInput", ...
                "expectedId", "aisdk:MCPClient:internalError"), ...
            "badCommand", struct( ...
                "identifier", "mcpclient_mex:badCommand", ...
                "expectedId", "aisdk:MCPClient:internalError"), ...
            "internalError", struct( ...
                "identifier", "mcpclient_mex:internalError", ...
                "expectedId", "aisdk:MCPClient:internalError"), ...
            "timeout", struct( ...
                "identifier", "mcpclient_mex:timeout", ...
                "expectedId", "aisdk:MCPClient:connectionTimeout"), ...
            "readFailure", struct( ...
                "identifier", "mcpclient_mex:read", ...
                "expectedId", "aisdk:MCPClient:serverError"), ...
            "spawnFailure", struct( ...
                "identifier", "mcpclient_mex:spawn", ...
                "expectedId", "aisdk:MCPClient:serverError"))
        NonAsciiText = struct( ...
            "accentedLatin", "café", ...
            "cjk", "東京", ...
            "emoji", "🎉", ...
            "mixed", "café 東京 🎉", ...
            "combiningMarks", "e" + char(769))
        ThrowServerErrorCase = struct( ...
            "badRequest", struct( ...
                "code", 400, ...
                "expectedId", "aisdk:MCPClient:badRequest"), ...
            "hostNotFound", struct( ...
                "code", 1003, ...
                "expectedId", "aisdk:MCPClient:hostNotFound"), ...
            "connectionRefused", struct( ...
                "code", 1004, ...
                "expectedId", "aisdk:MCPClient:connectionRefused"), ...
            "timeout", struct( ...
                "code", 1005, ...
                "expectedId", "aisdk:MCPClient:connectionTimeout"), ...
            "stdioNotFound", struct( ...
                "code", 1100, ...
                "expectedId", "aisdk:MCPClient:stdioNotFound"), ...
            "stdioPermission", struct( ...
                "code", 1101, ...
                "expectedId", "aisdk:MCPClient:stdioPermission"), ...
            "unknown", struct( ...
                "code", 1999, ...
                "expectedId", "aisdk:MCPClient:serverError"))
        ResolveTransportCase = struct( ...
            "autoHttpUrl", struct( ...
                "endpoint", "http://localhost:8080/mcp", ...
                "transport", "auto", ...
                "expectedType", "http", ...
                "expectedUrl", "http://localhost:8080/mcp", ...
                "expectedArgs", string.empty), ...
            "autoHttpsUrl", struct( ...
                "endpoint", "https://example.com/mcp", ...
                "transport", "auto", ...
                "expectedType", "http", ...
                "expectedUrl", "https://example.com/mcp", ...
                "expectedArgs", string.empty), ...
            "autoSseUrl", struct( ...
                "endpoint", "http://localhost:8080/sse", ...
                "transport", "auto", ...
                "expectedType", "sse", ...
                "expectedUrl", "http://localhost:8080/sse", ...
                "expectedArgs", string.empty), ...
            "autoSseUrlTrailingSlash", struct( ...
                "endpoint", "http://localhost:8080/sse/", ...
                "transport", "auto", ...
                "expectedType", "sse", ...
                "expectedUrl", "http://localhost:8080/sse/", ...
                "expectedArgs", string.empty), ...
            "autoUrlEndingInSseButNotPathSegment", struct( ...
                "endpoint", "https://example.com/analysse", ...
                "transport", "auto", ...
                "expectedType", "http", ...
                "expectedUrl", "https://example.com/analysse", ...
                "expectedArgs", string.empty), ...
            "autoFilePath", struct( ...
                "endpoint", "/usr/local/bin/my-server", ...
                "transport", "auto", ...
                "expectedType", "stdio", ...
                "expectedUrl", "/usr/local/bin/my-server", ...
                "expectedArgs", string.empty(1,0)), ...
            "autoFilePathWithArgs", struct( ...
                "endpoint", "/usr/local/bin/my-server --port 3000", ...
                "transport", "auto", ...
                "expectedType", "stdio", ...
                "expectedUrl", "/usr/local/bin/my-server", ...
                "expectedArgs", ["--port"; "3000"]), ...
            "explicitStreamableHttp", struct( ...
                "endpoint", "http://localhost:8080/mcp", ...
                "transport", "streamable-http", ...
                "expectedType", "http", ...
                "expectedUrl", "http://localhost:8080/mcp", ...
                "expectedArgs", string.empty), ...
            "explicitSse", struct( ...
                "endpoint", "http://localhost:8080/events", ...
                "transport", "sse", ...
                "expectedType", "sse", ...
                "expectedUrl", "http://localhost:8080/events", ...
                "expectedArgs", string.empty), ...
            "explicitStdio", struct( ...
                "endpoint", "/path/to/server", ...
                "transport", "stdio", ...
                "expectedType", "stdio", ...
                "expectedUrl", "/path/to/server", ...
                "expectedArgs", string.empty(1,0)))
        TransportMismatchCase = struct( ...
            "stdioWithHttpUrl", struct( ...
                "endpoint", "http://172.26.17.115:8765/mcp", ...
                "transport", "stdio", ...
                "expectedId", "aisdk:MCPClient:urlEndpointRequiresHttpTransport"), ...
            "stdioWithHttpsUrl", struct( ...
                "endpoint", "https://example.com/mcp", ...
                "transport", "stdio", ...
                "expectedId", "aisdk:MCPClient:urlEndpointRequiresHttpTransport"), ...
            "streamableHttpWithCommand", struct( ...
                "endpoint", "npx -y @modelcontextprotocol/server-everything", ...
                "transport", "streamable-http", ...
                "expectedId", "aisdk:MCPClient:httpTransportRequiresUrl"), ...
            "sseWithFilePath", struct( ...
                "endpoint", "/usr/local/bin/my-server", ...
                "transport", "sse", ...
                "expectedId", "aisdk:MCPClient:httpTransportRequiresUrl"))
    end

    methods (Test, TestTags = {'Unit'})
        function callTool_httpError_producesCorrectErrorId(testCase, HttpErrorCase)
            c = HttpErrorCase;
            client = aisdk.MCPClient("mock", Transport="mock");
            testCase.verifyError( ...
                @() client.callTool("__throw_http_error", "statusCode", c.statusCode), ...
                c.expectedId);
        end

        function throwServerError_producesCorrectErrorId(testCase, ThrowServerErrorCase)
            c = ThrowServerErrorCase;
            testCase.verifyError( ...
                @() aisdk.MCPClient.throwServerError(c.code, "test"), ...
                c.expectedId);
        end

        function throwMexError_producesCorrectErrorId(testCase, MexErrorCase)
            c = MexErrorCase;
            testCase.verifyError( ...
                @() aisdk.MCPClient.throwMexError( ...
                    MException(c.identifier, "%s", "test detail")), ...
                c.expectedId);
        end

        function throwMexError_localFault_keepsTheDetailedMessage(testCase)
            % A bad argument is a local fault, not a server error, and the
            % MEX message is the only thing that says which argument.
            err = testCase.captureError( ...
                @() aisdk.MCPClient.throwMexError(MException( ...
                    "mcpclient_mex:badInput", "%s", "Argument 2 must be a string")));
            testCase.verifySubstring(err.message, "Argument 2 must be a string");
        end

        function resolveTransport_detectsCorrectType(testCase, ResolveTransportCase)
            c = ResolveTransportCase;
            [type, url, args] = aisdk.MCPClient.resolveTransport( ...
                c.endpoint, c.transport);
            testCase.verifyEqual(type, c.expectedType);
            testCase.verifyEqual(url, c.expectedUrl);
            testCase.verifyEqual(args, c.expectedArgs);
        end

        function resolveTransport_stringArrayEndpoint_detectsStdio(testCase)
            [type, url, args] = aisdk.MCPClient.resolveTransport( ...
                ["/usr/local/bin/srv", "--verbose"], "auto");
            testCase.verifyEqual(type, "stdio");
            testCase.verifyEqual(url, "/usr/local/bin/srv");
            testCase.verifyEqual(args, "--verbose");
        end

        function resolveTransport_nonScalarEndpointWithHttp_errors(testCase)
            testCase.verifyError( ...
                @() aisdk.MCPClient.resolveTransport( ...
                    ["http://a", "http://b"], "sse"), ...
                "aisdk:MCPClient:nonScalarURL");
        end

        function resolveTransport_transportMismatch_errors(testCase, TransportMismatchCase)
            c = TransportMismatchCase;
            testCase.verifyError( ...
                @() aisdk.MCPClient.resolveTransport(c.endpoint, c.transport), ...
                c.expectedId);
        end

        function resolveTransport_transportMismatch_messageNamesAlternativeTransport(testCase)
            % The message must be actionable: it names the transport to use
            % instead. The endpoint is deliberately not quoted back, since
            % the caller just passed it in.
            err = testCase.captureError( ...
                @() aisdk.MCPClient.resolveTransport( ...
                    "http://localhost:8765/mcp", "stdio"));
            testCase.verifySubstring(err.message, "streamable-http");

            err = testCase.captureError( ...
                @() aisdk.MCPClient.resolveTransport("my-server --port 1", "sse"));
            testCase.verifySubstring(err.message, "stdio");
            % Also covers the placeholder actually being filled in.
            testCase.verifySubstring(err.message, "Transport=""sse""");
        end

    end

    methods (Access = private)
        function err = captureError(testCase, fcn)
            %captureError Return the MException thrown by FCN.
            try
                fcn();
                testCase.verifyFail("Expected the function to throw an error.");
                err = MException("aisdk:test:noError", "no error thrown");
            catch err
            end
        end
    end
end
