function [nodes, edges] = rxSignoffGraphDefinition(allTools, client)
%RXSIGNOFFGRAPHDEFINITION  The rxSignoff graph — node specs and edge topology.
%
%   [nodes, edges] = rxSignoffGraphDefinition(allTools, client) returns node definitions and
%   the edges that wire them into a DAG. This is the SerDes-specific
%   application of the +agentgraph framework.

% Copyright 2026 The MathWorks, Inc.

    arguments
        allTools (1,:) aisdk.tool.LLMTool
        client
    end
    nodes = [
        agentgraph.AgentNode("build", aisdk.AIAgent(client, ...
            Tools = selectTools(allTools, ["createSerdesSystem","configureChannel","configureAnalogModel", ...
                         "configureCTLE","configureDFECDR","configureVGA","configureFFE", ...
                         "getSystemState"]), ...
            SystemPrompt = readPrompt("build.md"), ...
            MaxIterations = 20), ...
            Description = "Build the SerDes system from the request (channel, " + ...
                "equalization). Usually reached only as an ancestor of a later goal.")

        agentgraph.AgentNode("analyse", aisdk.AIAgent(client, ...
            Tools = selectTools(allTools, ["runAnalysis","getAnalysisResults","getSystemState"]), ...
            SystemPrompt = readPrompt("analyse.md"), ...
            MaxIterations = 10), ...
            Description = "Run statistical analysis and read the reported eye metrics. " + ...
                "Drive here first to see if optimization is needed.")

        agentgraph.AgentNode("optimize", aisdk.AIAgent(client, ...
            Tools = selectTools(allTools, ["sweepParameter","optimizeWithGA","runAnalysis", ...
                         "getAnalysisResults","getSystemState","configureCTLE", ...
                         "configureDFECDR","configureFFE","configureVGA"]), ...
            SystemPrompt = readPrompt("optimize.md"), ...
            MaxIterations = 25), ...
            Description = "Optimize equalization: sweep parameters or run GA to maximize " + ...
                "eye height / COM. Drive here when the request asks for better metrics " + ...
                "and NOT for a plot -- if a plot is wanted too, drive to plot instead, " + ...
                "which optimizes on the way through.")

        agentgraph.AgentNode("plot", aisdk.AIAgent(client, ...
            Tools = selectTools(allTools, ["plotSerdesResults","plotSweepResults","getAnalysisResults", ...
                         "getSystemState"]), ...
            SystemPrompt = readPrompt("plot.md"), ...
            MaxIterations = 10), ...
            Description = "Produce the final eye diagram and measurements. Drive here " + ...
                "whenever the request mentions a plot, an eye diagram or a final " + ...
                "report -- optimization runs first as an ancestor, so this single " + ...
                "goal covers 'optimize AND plot'.")
    ];

    edges = [
        "build",    "analyse"
        "analyse",  "optimize"
        "optimize", "plot"
    ];
end

function tools = selectTools(allTools, names)
    tools = allTools(ismember([allTools.Name], names));
end

function p = readPrompt(filename)
    promptDir = fullfile(fileparts(mfilename('fullpath')), "prompts");
    p = string(fileread(fullfile(promptDir, filename)));
end
