classdef tmustBePositiveIntegerOrNaN < matlab.unittest.TestCase
% Tests for aisdk.llms.internal.mustBePositiveIntegerOrNaN.

%   Copyright 2026 The MathWorks, Inc.

    properties (TestParameter)
        validInput = struct( ...
            'nan',           {NaN}, ...
            'one',           {1}, ...
            'largeInt',      {128000})

        invalidInput = struct( ...
            'zero',          struct("value", 0,        "errID", "MATLAB:validators:mustBePositive"), ...
            'negative',      struct("value", -1,       "errID", "MATLAB:validators:mustBePositive"), ...
            'negativeInf',   struct("value", -inf,     "errID", "MATLAB:validators:mustBePositive"), ...
            'smallPositive', struct("value", eps,      "errID", "MATLAB:validators:mustBeInteger"), ...
            'nonInteger',    struct("value", 1.5,      "errID", "MATLAB:validators:mustBeInteger"), ...
            'positiveInf',   struct("value", inf,      "errID", "MATLAB:validators:mustBeInteger"), ...
            'string',        struct("value", "128000", "errID", "MATLAB:validators:mustBeNumeric"), ...
            'char',          struct("value", '128000', "errID", "MATLAB:validators:mustBeNumeric"))
    end

    methods (Test, TestTags = {'Unit'})
        function acceptsValidInput(testCase, validInput)
            testCase.verifyWarningFree( ...
                @() aisdk.llms.internal.mustBePositiveIntegerOrNaN(validInput));
        end

        function rejectsInvalidInput(testCase, invalidInput)
            testCase.verifyError( ...
                @() aisdk.llms.internal.mustBePositiveIntegerOrNaN(invalidInput.value), ...
                invalidInput.errID);
        end
    end
end
