function mock = createMathMCPMock()
%createMathMCPMock Create a mcpHTTPClientMock with add/multiply tools.
%   Used by tExamples to mock the MCP server for MCPClientAndAgentTools.

%   Copyright 2026 The MathWorks, Inc.

serverTools = { ...
    struct("name", "addTwoNumbers", ...
        "description", "Add two numbers together", ...
        "inputSchema", struct( ...
            "properties", struct( ...
                "a", struct("type","integer","title","A"), ...
                "b", struct("type","integer","title","B")), ...
            "required", {{"a","b"}}, ...
            "title", "addTwoNumbersArguments", ...
            "type", "object")), ...
    struct("name", "multiplyTwoNumbers", ...
        "description", "Multiply two numbers together", ...
        "inputSchema", struct( ...
            "properties", struct( ...
                "a", struct("type","integer","title","A"), ...
                "b", struct("type","integer","title","B")), ...
            "required", {{"a","b"}}, ...
            "title", "multiplyTwoNumbersArguments", ...
            "type", "object"))};

mock = mcpHTTPClientMock(serverTools, @callToolFcn);

end

function result = callToolFcn(name, args)
    switch name
        case "addTwoNumbers"
            result = string(args.a + args.b);
        case "multiplyTwoNumbers"
            result = string(args.a * args.b);
    end
end
