classdef tmustBeApprovalDecision < matlab.unittest.TestCase
% Tests for aisdk.internal.mustBeApprovalDecision.

%   Copyright 2026 The MathWorks, Inc.

    methods (Test, TestTags = {'Unit'})
        function acceptsApproval(testCase)
            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Permanent", false, "Reason", "")));
        end

        function acceptsDenialWithReason(testCase)
            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", false, "Permanent", false, "Reason", "not safe")));
        end

        function acceptsCharReason(testCase)
            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Permanent", false, "Reason", 'not safe')));
        end

        function acceptsEmptyCharReason(testCase)
            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Permanent", false, "Reason", '')));
        end

        function acceptsExtraFields(testCase)
            % The contract fixes the fields a decision must have, not the
            % fields it may have.
            decision = struct("Approved", true, "Permanent", false, ...
                "Reason", "", "DecidedBy", "reviewer");

            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeApprovalDecision(decision));
        end

        function acceptsFieldsInAnyOrder(testCase)
            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Reason", "", "Permanent", true, "Approved", true)));
        end

        function rejectsLogical(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision(true), ...
                "aisdk:agent:approvalDecisionNotStruct");
        end

        function rejectsString(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision("approved"), ...
                "aisdk:agent:approvalDecisionNotStruct");
        end

        function rejectsEmptyStruct(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision(struct("Approved", {})), ...
                "aisdk:agent:approvalDecisionNotStruct");
        end

        function rejectsStructArray(testCase)
            decisions = [struct("Approved", true, "Permanent", false, "Reason", ""), ...
                         struct("Approved", false, "Permanent", false, "Reason", "")];

            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision(decisions), ...
                "aisdk:agent:approvalDecisionNotStruct");
        end

        function rejectsMissingApproved(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Permanent", false, "Reason", "")), ...
                "aisdk:agent:approvalDecisionMissingField");
        end

        function rejectsMissingPermanent(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Reason", "")), ...
                "aisdk:agent:approvalDecisionMissingField");
        end

        function rejectsMissingReason(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Permanent", false)), ...
                "aisdk:agent:approvalDecisionMissingField");
        end

        function rejectsNumericApproved(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", 1, "Permanent", false, "Reason", "")), ...
                "aisdk:agent:approvalDecisionFlagNotLogical");
        end

        function rejectsTextApproved(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", "true", "Permanent", false, "Reason", "")), ...
                "aisdk:agent:approvalDecisionFlagNotLogical");
        end

        function rejectsNonScalarApproved(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", [true false], "Permanent", false, "Reason", "")), ...
                "aisdk:agent:approvalDecisionFlagNotLogical");
        end

        function rejectsNumericPermanent(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Permanent", 0, "Reason", "")), ...
                "aisdk:agent:approvalDecisionFlagNotLogical");
        end

        function rejectsEmptyApproved(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", logical.empty, "Permanent", false, "Reason", "")), ...
                "aisdk:agent:approvalDecisionFlagNotLogical");
        end

        function rejectsNumericReason(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Permanent", false, "Reason", 42)), ...
                "aisdk:agent:approvalDecisionReasonNotText");
        end

        function rejectsEmptyStringReason(testCase)
            % string.empty is 0x0, which is not the same thing as "".
            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision( ...
                    struct("Approved", true, "Permanent", false, ...
                        "Reason", string.empty)), ...
                "aisdk:agent:approvalDecisionReasonNotText");
        end

        function rejectsMultilineStringReason(testCase)
            decision = struct("Approved", true, "Permanent", false);
            decision.Reason = ["first line"; "second line"];

            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision(decision), ...
                "aisdk:agent:approvalDecisionReasonNotText");
        end

        function rejectsCellReason(testCase)
            decision = struct("Approved", true, "Permanent", false);
            decision.Reason = {'not safe'};

            testCase.verifyError( ...
                @() aisdk.internal.mustBeApprovalDecision(decision), ...
                "aisdk:agent:approvalDecisionReasonNotText");
        end
    end
end
