classdef tmustBeValidPenalty < matlab.unittest.TestCase
% Tests for aisdk.internal.mustBeValidPenalty.

%   Copyright 2026 The MathWorks, Inc.

    properties (TestParameter)
        validInput = struct( ...
            'autoString', {"auto"}, ...
            'autoChar', {'auto'}, ...
            'zero', {0}, ...
            'lowerBound', {-2}, ...
            'upperBound', {2})
    end

    methods (Test, TestTags = {'Unit'})
        function acceptsValidInput(testCase, validInput)
            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeValidPenalty(validInput));
        end

        function rejectsBelowLowerBound(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeValidPenalty(-2.1), ...
                "MATLAB:notGreaterEqual");
        end

        function rejectsAboveUpperBound(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeValidPenalty(2.1), ...
                "MATLAB:notLessEqual");
        end

        function rejectsNonScalar(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeValidPenalty([0 1]), ...
                "MATLAB:expectedScalar");
        end

        function rejectsSparse(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeValidPenalty(sparse(1)), ...
                "MATLAB:expectedNonsparse");
        end

        function rejectsComplex(testCase)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeValidPenalty(1+2i), ...
                "MATLAB:expectedReal");
        end
    end
end
