classdef tmustBeValidToolCallID < matlab.unittest.TestCase
% Tests for aisdk.internal.mustBeValidToolCallID.

%   Copyright 2026 The MathWorks, Inc.

    properties (TestParameter)
        validInput = struct( ...
            'scalarString', {"hello"}, ...
            'emptyScalarString', {""})
        invalidInput = struct( ...
            'doubleEmpty', {[]}, ...
            'emptyChar', {''}, ...
            'charVector', {'abc'}, ...
            'numericScalar', {0}, ...
            'stringArray', {["a","b"]})
    end

    methods (Test, TestTags = {'Unit'})
        function acceptsValidInput(testCase, validInput)
            testCase.verifyWarningFree( ...
                @() aisdk.internal.mustBeValidToolCallID(validInput));
        end

        function rejectsInvalidInput(testCase, invalidInput)
            testCase.verifyError( ...
                @() aisdk.internal.mustBeValidToolCallID(invalidInput), ...
                "aisdk:message:InvalidToolCallID");
        end
    end
end
